//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.19 at 07:13:45 PM IST 
//


package org.sreenutech.ordersres;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.sreenutech.ordersres package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OrderRes_QNAME = new QName("http://www.sreenutech.org/OrdersRes", "OrderRes");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.sreenutech.ordersres
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrderRestype }
     * 
     */
    public OrderRestype createOrderRestype() {
        return new OrderRestype();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderRestype }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sreenutech.org/OrdersRes", name = "OrderRes")
    public JAXBElement<OrderRestype> createOrderRes(OrderRestype value) {
        return new JAXBElement<OrderRestype>(_OrderRes_QNAME, OrderRestype.class, null, value);
    }

}
