//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.19 at 07:13:45 PM IST 
//


package org.sreenutech.ordersreq;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.sreenutech.ordersreq package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OrderReq_QNAME = new QName("http://www.sreenutech.org/OrdersReq", "OrderReq");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.sreenutech.ordersreq
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrderReqtype }
     * 
     */
    public OrderReqtype createOrderReqtype() {
        return new OrderReqtype();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderReqtype }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sreenutech.org/OrdersReq", name = "OrderReq")
    public JAXBElement<OrderReqtype> createOrderReq(OrderReqtype value) {
        return new JAXBElement<OrderReqtype>(_OrderReq_QNAME, OrderReqtype.class, null, value);
    }

}
